[project]
name = "udemy-purchase-scraper"
version = "0.0.1"
description = "Scrapes Udemy for purchases"
authors = [
    {name = "Garrett Johnson",email = "pingujohnson@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.15"
dependencies = [
    "beautifulsoup4",
    "fake-useragent",
    "ipython",
    "numpy",
    "pandas",
    "python-dotenv",
    "requests",
    "selenium",
    "undetected-chromedriver"
]

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel"
]
